DigitalLeap/DigitalLeap.Web/Controllers/FeaturesController.cs
using System;
using System.Web.Mvc;
using DigitalLeap.Domain.Model;
using DigitalLeap.Services;

namespace DigitalLeap.Web.Controllers
{
    public class FeaturesController : Controller
    {
        private readonly IEnquiryService _enquiryService;

        public FeaturesController(IEnquiryService enquiryService)
        {
            _enquiryService = enquiryService;
        }
        // GET: Home
        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Capabilities()
        {
            return View();
        }
        public ActionResult ChoosePlan()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View(new ContactInformation());
        }

        [HttpPost]
        public PartialViewResult ContactUs(ContactInformation model)
        {
            string error;

            if (ModelState.IsValid)
            {
                try
                {
                    _enquiryService.Save(model);

                    // Success
                    return PartialView("FormResult", string.Empty);
                }
                catch (Exception e)
                {
                    error = e.Message;
                }
            }
            else
            {
                error = "The Model is invalid";
            }

            return PartialView("FormResult", error);
        }
    }
}

DigitalLeap/DigitalLeap.Web/Views/Features/AboutUs.cshtml
@model dynamic

@{
	ViewBag.Title = "WHO WE ARE";
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
}
@section Banner
{
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<div class="front-banner">
					<div class="main-text-banner">
						<div class="vertical-text">
							Digital Leap 2017
						</div>
						<h1>Who we are</h1>
						<p>We are Sitecore oriented digital agency which helps our clients to take comprehensive benefits from the Sitecore platform and make sure that their solutions meet their business expectations.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
}
    
	<div class="container fp-capabilities">
        <div class="row">
            <div class="col-xs-1 col-sm-6 col-md-6 col-lg-4 no-gutters clearfix">
                <div class="row">
                    <div class="col-xs-1 col-sm-1 col-md-12 col-lg-12 capabilities-item">
                        <img class="icon-copabilities" src="img/development-01.svg" alt="">
                        <h3>Solution Development</h3>
                        <p>Sitecore gives customers unlimited opportunities to digitalize their business. Starting from professional content management, Sitecore allows customers to introduce personalization, gather visitor experience and promote it according to the business needs. Sitecore® Experience Accelerator (SXA) helps significantly decrease time to market and let our clients meet their business expectations.</p>
                        <p>Your initial Sitecore implementation is extremely important as it creates the foundation for your future digital journey. To succeed with this complex task you need a trusted partner that has experience in building custom solutions.</p>
                    </div>
                </div>
            </div>
            <div class="col-xs-1 col-sm-6 col-md-6 col-lg-8 no-gutters clearfix">
                <div class="row">
                <div class="col-xs-1 col-sm-6 col-md-6 col-lg-6 capabilities-item">
                    <img class="icon-copabilities" src="img/content_migration-01.svg" alt="">
                    <h3>Content Migration</h3>
                    <p>Many organizations that decided to get digitally with Sitecore already have presence of its content at WEB. We have necessary competencies to migrate your existing solution to Sitecore platform.</p>
                </div>
                <div class="col-xs-1 col-sm-6 col-md-6 col-lg-6 capabilities-item">
                    <img class="icon-copabilities" src="img/integration-01.svg" alt="">
                    <h3>Integration</h3>
                    <p>Sitecore solution is more than just CMS. It requires integration with different company infrastructural systems or third party services. We can build bridges between Sitecore platform and other services inside or outside client company.</p>
                </div>
                <div class="col-xs-1 col-sm-6 col-md-6 col-lg-6 capabilities-item">
                    <img class="icon-copabilities" src="img/solution_audit-01.svg" alt="">
                    <h3>Solution Audit</h3>
                    <p>For companies that already have a Sitecore solution, it is vital to understand the health of the system as a whole before introducing new business features. We provide auditing services including verification of a company digital system to make sure it follows Sitecore best practices.</p>
                </div>
                <div class="col-xs-1 col-sm-6 col-md-6 col-lg-6 capabilities-item">
                    <img class="icon-copabilities" src="img/upgrade-01.svg" alt="">
                    <h3>Upgade</h3>
                    <p>Every new version of Sitecore Platform brings something spectacular. Following to Sitecore Platform helps clients to streamline their digital journey, it is important to follow this trend. Our company provides services of upgrading your solution to a new version of Sitecore Platform and configuring it to prepare the company for the next digital leap.</p>
                </div>

                </div>
            </div>

DigitalLeap/DigitalLeap.Web/Views/Features/Capabilities.cshtml
@model dynamic

@{
	ViewBag.Title = "Capabilities";
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
	ViewBag.ContainerClass = "capabilities-banner";
}

<div class="container content-margin capabilities-list">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 capabilities-item ">
			<div class="panel-dl">
				<img class="icon-copabilities" src="../../img/content_migration-01.svg" alt="">
				<h3>Content Migration</h3>
				<ul class="list-mark-v">
					<li>Storage that’s lightning fast</li>
					<li>Accelerate your every move</li>
					<li>More colors than ever</li>
					<li>Double the speed and bandwidth</li>
				</ul>
			</div>
		</div>
		<div class="col-xs-1 col-sm-6 col-md-6 col-lg-3 capabilities-item">
			<div class="panel-dl">
				<img class="icon-copabilities" src="../../img/solution_audit-01.svg" alt="">
				<h3>Solution Audit</h3>
				<ul class="list-mark-v">
					<li>Review configuration and log files on the matter of apporpriate using for specific application setup</li>
					<li>Review of the solution architecture</li>
					<li>Performance Audit</li>
					<li>Security Audit</li>
				</ul>
				<hr>
				<div class="text-center">
					<button onclick="window.location.href = '@Url.Action("ChoosePlan", "Features")'" type="button" class="btn btn-primary btn-lg blue-btn">View Plans</button>
				</div>
			</div>
		</div>
		<div class="col-xs-1 col-sm-6 col-md-6 col-lg-3 capabilities-item">
			<div class="panel-dl">
				<img class="icon-copabilities" src="../../img/upgrade-01.svg" alt="">
				<h3>Upgade</h3>
				<ul class="list-mark-v">
					<li>Installing upgrade packages</li>
					<li>Resolving upgrade conflicts</li>
					<li>Configure the new instance according to the best practices of a current version</li>
				</ul>
			</div>
		</div>
		<div class="col-xs-1 col-sm-6 col-md-6 col-lg-3 capabilities-item">
			<div class="panel-dl">
				<img class="icon-copabilities" src="../../img/integration-01.svg" alt="">
				<h3>Integration</h3>
				<ul class="list-mark-v">
					<li>Creating integration between Sitecore solutions and third party applications</li>
				</ul>
			</div>
		</div>
	</div>
</div>

DigitalLeap/DigitalLeap.Web/Views/Features/ChoosePlan.cshtml
@model dynamic

@{
	ViewBag.Title = "Choose a plan";
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
	ViewBag.ContainerClass = "choose-plan-banner";
}

<div class="container content-margin choose-paln">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-6 offset-lg-2 col-lg-4 choose-paln-item">
			<div class="panel-dl">
				<div class="plan-name">Basic</div>
				<div class="price-plan">
					<div class="dollar">$</div>
					<div class="price">0</div>
					<div class="month">/ mo</div>
				</div>
				<hr>
				<ul class="list-mark-v">
					<li>Storage that’s lightning fast</li>
					<li>Accelerate your every move</li>
					<li>More colors than ever</li>
					<li class="disable-option">Double the speed and bandwidth</li>
				</ul>
				<hr>
				<div class="text-center">
					<button type="button" class="btn btn-outline-primary btn-lg blue-btn-outline">Choose Plan</button>
				</div>
			</div>
		</div>
		<div class="col-xs-1 col-sm-6 col-md-6 col-lg-4 choose-paln-item ">
			<div class="panel-dl">
				<div class="plan-name">Premium</div>
				<div class="price-plan">
					<div class="dollar">$</div>
					<div class="price">49</div>
					<div class="month">/ mo</div>
				</div>
				<hr>
				<ul class="list-mark-v">
					<li>Storage that’s lightning fast</li>
					<li>Accelerate your every move</li>
					<li>More colors than ever</li>
					<li>Double the speed and bandwidth</li>
				</ul>
				<hr>
				<div class="text-center">
					<button type="button" class="btn btn-primary btn-lg blue-btn">Choose Plan</button>
				</div>
			</div>
		</div>
	</div>
</div>

DigitalLeap/DigitalLeap.Web/Views/Features/ContactUs.cshtml
@model DigitalLeap.Domain.Model.ContactInformation

@{
	ViewBag.Title = "Contact Us";
	Layout = "~/Views/Shared/_ContentLayout.cshtml";
	ViewBag.ContainerClass = "contact-banner";
}

<div class="container content-margin contact">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-6 col-md-12 offset-lg-3 col-lg-6">
			<div class="panel-dl contact-form">
				<div class="icon"><img src="../../img/mail-01.svg" alt=""></div>
				<div id="formResult"></div>
				@using (Ajax.BeginForm("ContactUs", "Features", FormMethod.Post, new AjaxOptions {UpdateTargetId = "formResult" }, new {@id="ContactFormId"}))
				{
					<div class="form-group">
						@Html.LabelFor(m => m.FullName)
						@Html.TextBoxFor(m => m.FullName, new {@class="form-control"})
						@Html.ValidationMessageFor(m => m.FullName)
						@*<label for="fullName">Full Name</label>
						<input type="text" class="form-control" id="fullName" placeholder="">*@
					</div>
					<div class="form-group">
						@Html.LabelFor(m => m.Email)
						@Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
						@Html.ValidationMessageFor(m => m.Email)
						@*<label for="emailAdress">Email Adress</label> 
						<input type="email" class="form-control" id="emailAdress" aria-describedby="emailHelp" placeholder="">*@
					</div>
					<div class="form-group">
						@Html.LabelFor(m => m.Comments)
						@Html.TextAreaFor(m => m.Comments, new { @class = "form-control", rows="4" })
						@*<label for="commentsTextarea">Comments</label>
						<textarea class="form-control" id="commentsTextarea" rows="4"></textarea>*@
					</div>
					<div class="text-center">
						<button type="submit" class="btn btn-primary btn-lg blue-btn">Send Your Message</button>
					</div>
				}
			</div>
		</div>
	</div>
</div>
@section Scripts {
	<script type="text/javascript">
		//$(document).ready(function() {
		//	$("#ContactFormId").submit(function(event) {
		//		event.preventDefault();
		//		event.stopImmediatePropagation();
		//		var action = $("#ContactFormId").attr("action");
		//		// Setting.  
		//		var dataString = new FormData($("#ContactFormId").get(0));
		//		contentType = false;
		//		processData = false;
		//		$.ajax({
		//			type: "POST",
		//			url: action,
		//			data: dataString,
		//			dataType: "json",
		//			contentType: contentType,
		//			processData: processData,
		//			success: function(result) {
		//				// Result.  
		//				onAjaxRequestSuccess(result);
		//			},
		//			error: function(jqXHR, textStatus, errorThrown) {
		//				//do your own thing  
		//				alert("fail");
		//			}
		//		});
		//	}); //end .submit() 

		//	var onAjaxRequestFailure = function (jqXHR, textStatus, errorThrown) { alert("Error!"); }

		//	var onAjaxRequestSuccess = function (result) {
		//		alert("Success!");

		//	}
		//});

		function onAjaxRequestFailure(parameters) {
			alert("Failure");
		}
		function onAjaxRequestSuccess(parameters) {
			alert("Success");
		}
	</script>
}

DigitalLeap/DigitalLeap.Web/Views/Shared/FormResult.cshtml
@model string
@{
	var isSuccessful = string.IsNullOrEmpty(Model);
	var alertAttribute = isSuccessful ? "alert alert-success" : "alert alert-danger";
	var prefixText = isSuccessful ? "Thank you!" : "Oops!";
	var text = isSuccessful ? "Your information was saved." : Model;
}
<div class="@alertAttribute" role="alert">
	<strong>@prefixText</strong>&nbsp;@text
</div>

DigitalLeap/DigitalLeap.Web/Views/Shared/_ContentLayout.cshtml
<!doctype html>
<html lang="en">

<head>
	<title>@ViewBag.Title</title>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<!-- Favicon -->
	<link rel="icon" type="image/png" href="/img/favicon.png" />    
	<!-- Main CSS -->
	<link rel="stylesheet" href="../../Css/main.css">
	<!-- Google fonts -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">

</head>

<body>
<!--    Navigation-->
<div class="nav-line-bg">
	<nav class="navbar navbar-expand-md navbar-light">
		<a class="navbar-brand" href="@Url.Action("AboutUs", "Features")"><img src="../../img/logo_dl-01.svg" height="30" alt="Logo"></a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
			<ul class="navbar-nav">
				<li class="nav-item @(ViewContext.RouteData.Values["Action"].ToString() == "AboutUs" ? "active" : "")">
					@Html.ActionLink("Agency", "AboutUs", "Features", null, new { @class = "nav-link" })
				</li>
		
				<li class="nav-item @(ViewContext.RouteData.Values["Action"].ToString() == "ContactUs" ? "active" : "")">
					@Html.ActionLink("Contact Us", "ContactUs", "Features", null, new { @class = "nav-link" })
				</li>
			</ul>
		</div>
	</nav>
</div>
	
	@if (!IsSectionDefined("Banner"))
	{
		<div class="@ViewBag.ContainerClass">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
						<div class="title-banner">
							<h2>@ViewBag.Title</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	}
	else
	{
		@RenderSection("Banner", true)
	}


@RenderBody()

    
<div class="container footer-con">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<hr>
			<div class="copyright">Digital Leap &copy; 2017</div>
		</div>
	</div>
</div>
    
<!-- Bootstrap -->
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js" type="text/javascript"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery-ajax-unobtrusive@3.2.4/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

@*<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>

<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@

	<script src=""></script>
	<script src=""></script>
	<script src=""></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
@RenderSection("scripts", false)
</body>

</html>